### ISSUE TITLE
usage of calibration files and SXGA image_mode produces false clouds

### ISSUE THREAD

**Issue by loam** [piyushk/freenect_stack#11]
I noticed a problem calling freenect-registered-xyzrgb.launch (SXGA image_mode) and using custom calibration files:  http://pastebin.com/XfvuDYTJ. The produced cloud seems to contain just 1/4 of the actual data. The cloud does look fine if no calib files are used.

**Comment by piyushk** [comment]
I just got around to fixing this error. Apologies for the long delay. Unfortunately, the pastebin link no longer works. If you wish to reopen this error, please reopen the error report here: https://github.com/ros-drivers/freenect_stack/issues/1
