### ISSUE TITLE
dynamic configure doesn't take into account some parameters

### ISSUE THREAD

**Issue by filipnovotny** [piyushk/freenect_stack#2]
When I do rosrun dynamic_configure configure_gui and want to change the resolution on /camera/driver by setting depth_mode to  QVGA30Hz (5) it doesn't do anything and returns to the default resolution (2).
The problem is that default resolution just isn't an option for some people (for example https://code.ros.org/gf/project/ros/mailman/?_forum_action=ForumMessageBrowse&thread_id=62167&action=ListThreads&mailman_id=39) because it's too slow.
It also makes makes something crash as a result of this change:
[lagadic-wifi-0]: [camera_nodelet_manager-1] process has died [pid 7735, exit code -11, cmd /opt/ros/fuerte/stacks/nodelet_core/nodelet/bin/nodelet manager __name:=camera_nodelet_manager __log:=/home/fnovotny/.ros/log/af902254-1929-11e2-b6d9-001ec953af27/camera_nodelet_manager-1.log].

**Comment by piyushk** [comment]
Thanks for reporting this. I haven't tested everything yet, will do so soon
enough. The crash is probably because of the lack of thread safety at the
moment. Both issues should be fixed in the next day or two.

**Comment by piyushk** [comment]
I am fixing dynamic reconfigure. However it seems like libfreenect does support QVGA at all. See https://github.com/OpenKinect/libfreenect/issues/306
https://groups.google.com/forum/#!msg/openkinect/BCzGN1Zh1Gw/lqgduCdmb30J

If the Kinect natively supports the low resolution, I suspect the OpenKinect folks were not able to reverse engineer it. This will significantly delay QVGA introduction, as we have other pending tasks that we'll need to deal with first. I think the easiest way to do this is to get the driver to resize the image/focal length etc and then publish. Should still be computationally efficient.

I'll file a separate enhancement ticket for this feature.

**Comment by piyushk** [comment]
dynamic reconfigure is now working as expected. Unfortunately, QVGA resolution is not currently supported.
