### ISSUE TITLE
ERROR: Tried to advertise a service that is already advertised in this node 

### ISSUE THREAD

**Issue by cberner** [piyushk/freenect_stack#3]
When I launch freenect I get these error messages:

[ERROR] [1351056483.202694643]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/compressedDepth/set_parameters]
[ERROR] [1351056483.211906639]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/compressed/set_parameters]
[ERROR] [1351056483.222372491]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/theora/set_parameters]

It seems like they're harmless, since it works anyway. Thanks for the new driver! :)

**Comment by piyushk** [comment]
I've documented this here: http://www.ros.org/wiki/openni_launch#Error_during_launch

It is not specific to libfreenect, but how the openni_launch files were designed. We'll have to do a review before we figure out how to get rid of them.

I'll close this for now. We can reopen this if and when we decide to fix it.

**Comment by tanisha33** [comment]
I am getting the same error how to fix it during openni launch:

[ WARN] [1444207844.971468935]: Camera calibration file /home/tanisha/.ros/camera_info/rgb_A00363A09463113A.yaml not found.
[ WARN] [1444207844.971540989]: Using default parameters for RGB camera calibration.
[ WARN] [1444207844.971599938]: Camera calibration file /home/tanisha/.ros/camera_info/depth_A00363A09463113A.yaml not found.
[ WARN] [1444207844.971642796]: Using default parameters for IR camera calibration.
[ERROR] [1444207847.792562639]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/compressedDepth/set_parameters]
[ERROR] [1444207847.867052204]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/compressed/set_parameters]
[ERROR] [1444207848.009323466]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/theora/set_parameters]

**Comment by yingli666** [comment]
Have you solve the question?The question has confused me two weeks.
