### ISSUE TITLE
Error: unable to open specified kinect

### ISSUE THREAD

**Issue by jonazpiazu** [piyushk/freenect_stack#7]
I am getting the following error when trying to run "roslaunch freenect_launch freenect.launch":

[ INFO] [1353341052.550691073]: Number devices connected: 1
[ INFO] [1353341052.551223916]: 1. device on bus 000:00 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id 'A00362901041044A'
[ INFO] [1353341052.552628239]: Searching for device with index = 1
[ INFO] [1353341052.557102305]: No matching device found.... waiting for devices. Reason: [ERROR] Unable to open specified kinect

The standard demo applications from freenect such as freenect-glview work correctly.

Thanks

**Comment by piyushk** [comment]
Could you post the output of the command:

```
rosrun libfreenect glview
```

This just checks whether our locally built copy of libfreenect works as well. Also:
1. What version of Ubuntu/ROS are you using?
2. Are you testing over a USB 2.0 port?

**Comment by piyushk** [comment]
changing status to closed for insufficient information. If further information is available, we can reopen this issue again.

**Comment by sindljan** [comment]
Hi I have the same problem...
here is some information:
  System: Ubuntu Precise 12.04 (hosted by VMware on win7 32b)
  ROS: Fuerte 1.8.10
I expect that Kinect runs on USB 2.0. Here is the output of lsusb:
  Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
  Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
  Bus 001 Device 008: ID 045e:02ae Microsoft Corp. Xbox NUI Camera
  Bus 002 Device 002: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Output of rosrun libfreenect glview:
  Kinect camera test
  Number of devices found: 1
  Could not open device

I have also try to run this command under the admin rights and it didn't help. I have try to use Kinect under the windows and there everything works fine. It only means, that the connectinon between computer and Kinect works fine.

**Comment by sindljan** [comment]
Some more information about connected Kinect:
Bus 001 Device 002: ID 045e:02ae Microsoft Corp. Xbox NUI Camera
Device Descriptor:
--bLength               18
--bDescriptorType       1
--bcdUSB            2.00
--bDeviceClass          0 (Defined at Interface level)
--bDeviceSubClass       0
--bDeviceProtocol       0
--bMaxPacketSize0       64
--idVendor          0x045e Microsoft Corp.
--idProduct         0x02ae Xbox NUI Camera
--bcdDevice         1.0b
--iManufacturer         2 Microsoft
--iProduct              1 Xbox NUI Camera
--iSerial               3 A00364914549043A
--bNumConfigurations    1
--Configuration Descriptor:
------bLength               9
------bDescriptorType       2
------wTotalLength          32
------bNumInterfaces        1
------bConfigurationValue   1
------iConfiguration        0
------bmAttributes      0xc0
------Self Powered
------MaxPower              16mA
------Interface Descriptor:
--------bLength                 9
--------bDescriptorType         4
--------bInterfaceNumber        0
--------bAlternateSetting       0
--------bNumEndpoints           2
--------bInterfaceClass     255 Vendor Specific Class
--------bInterfaceSubClass  255 Vendor Specific Subclass
--------bInterfaceProtocol  255 Vendor Specific Protocol
--------iInterface              0
--------Endpoint Descriptor:
--------bLength                 7
--------bDescriptorType         5
--------bEndpointAddress    0x81  EP 1 IN
--------bmAttributes            1
--------Transfer Type           Isochronous
--------Synch Type              None
--------Usage Type              Data
--------wMaxPacketSize  0x0bc0  2x 960 bytes
--------bInterval               1
--------Endpoint Descriptor:
--------bLength                 7
--------bDescriptorType         5
--------bEndpointAddress    0x82  EP 2 IN
--------bmAttributes            1
--------Transfer Type           Isochronous
--------Synch Type              None
--------Usage Type              Data
--------wMaxPacketSize  0x0bc0  2x 960 bytes
--------bInterval               1
Device Qualifier (for other device speed):
--bLength               10
--bDescriptorType       6
--bcdUSB            2.00
--bDeviceClass          0 (Defined at Interface level)
--bDeviceSubClass       0
--bDeviceProtocol       0
--bMaxPacketSize0       64
--bNumConfigurations    1
Device Status:  0x0001
--Self Powered

**Comment by sindljan** [comment]
Ok It's working now. It's probably a speciality of virtual machine. You have to connect all USB devices that Kinect offeres. These are kinect audio, kinect camera and motors. If you connect them all it start working.

**Comment by piyushk** [comment]
Thanks for the update. I've added a note here: http://www.ros.org/wiki/freenect_stack
